language: node_js

node_js:
  - "stable"

before_install:
  # update first
  - sudo apt-get update -qq
  # install Chinese fonts
  - sudo apt-get install -y fonts-arphic-gbsn00lp
  # Install Gitbook
  - npm install gitbook-cli -g
  - npm install svgexport -g
  # Clone the repository
  - cd ~
  - git clone --depth=10 --branch=master git://github.com/billryan/programming-notes.git

before_script:
  # install calibre latest version
  - sudo -v && wget --no-check-certificate -nv -O- https://raw.githubusercontent.com/kovidgoyal/calibre/master/setup/linux-installer.py | sudo python -c "import sys; main=lambda:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main()"
  # install qiniu sync
  - wget http://devtools.qiniu.io/qiniu-devtools-linux_amd64-current.tar.gz
  - tar xfz qiniu-devtools-linux_amd64-current.tar.gz
  - cp programming-notes/conf/qiniu_sync.json ~/

script:
  # replace with real key
  - sed -i "s/AccessKey/$QAK/g" qiniu_sync.json
  - sed -i "s/SecretKey/$QSK/g" qiniu_sync.json
  - mkdir -p ~/upload
  - cd ~/programming-notes
  - gitbook install
  - gitbook build ./ --format=json
  - gitbook build ./ 
  - gitbook pdf ./ ~/upload/programming_notes_billryan_print.pdf
  - gitbook epub ./ ~/upload/programming_notes_billryan.epub
  - gitbook mobi ./ ~/upload/programming_notes_billryan.mobi

after_success:
  # copy website html files to upload
  - tar czf programming_notes_billryan_html.tar.gz _book/
  - cp programming_notes_billryan_html.tar.gz ~/upload/
  # upload to qiniu
  - ~/qrsync ~/qiniu_sync.json
    #  # cd ~
    #  - cd ~
    #  # install source code pro
    #  - mkdir -p /tmp/code_pro
    #  - cd /tmp/code_pro/
    #  - wget https://github.com/adobe-fonts/source-code-pro/archive/1.017R.tar.gz
    #  - tar xzf 1.017R.tar.gz
    #  - mkdir -p ~/.fonts/fontconfig/conf.d/
    #  - cp source-code-pro-1.017R/OTF/*.otf ~/.fonts/
    #  - sudo fc-cache -f -v
    #  # install google noto Simplified Chinese
    #  - mkdir -p /tmp/noto
    #  - cd /tmp/noto
    #  - wget https://www.google.com/get/noto/pkgs/NotoSansCJKSC-hinted.zip 
    #  - https://www.google.com/get/noto/pkgs/NotoSerif-unhinted.zip
    #  - unzip NotoSansCJKSC-hinted.zip
    #  - unzip NotoSerif-unhinted.zip
    #  - mkdir -p ~/.fonts/noto
    #  - mv *.otf ~/.fonts/noto
    #  # update fonts
    #  - cd ~
    #  - cp ~/algorithm-exercise/conf/10-latin.conf ~/.fonts/fontconfig/conf.d/
    #  - cp ~/algorithm-exercise/conf/15-noto-cjksc.conf ~/.fonts/fontconfig/conf.d/
    #  - cp ~/algorithm-exercise/conf/20-noto-cjk.conf ~/.fonts/fontconfig/conf.d/
    #  - sudo fc-cache -f -v
    #  # generate different locales
    #  - sudo locale-gen zh_CN.UTF-8
    #  - cd ~/algorithm-exercise
    #  - export LANG=zh_CN.UTF-8
    #  - gitbook pdf ./ ~/upload/algorithm_billryan_desktop.pdf
    #  - ~/qrsync ~/qiniu_sync.json

branches:
  only:
    - master
